### ISSUE TITLE
Wi-Fi - 802.11 captures support

### ISSUE THREAD

**Issue by lealog** [brimsec/brim#570] opened 2020-04-08 01:06 UTC
Can it be possible to support Wi-Fi (802.11) captures.
I have tested Wi-Fi captures and it seems that is not supported.

**Comment by philrz** [comment] 2020-04-08 01:13
@lealog: Would it be possible to share a non-sensitive sample capture? We certainly intend to support as many capture formats as possible, so if there's a corner case that's unique to the capture format you're using, we'd like to be able to reproduce that in-house and see if we can address it. If you don't feel comfortable attaching it to a GitHub Issue you could also ping us on our [public Slack](https://join.slack.com/t/brimsec/shared_invite/zt-cy34xoxg-hZiTKUT~1KdGjlaBIuUUdg) and we could receive it from you in a private chat or you could email it to us at support@brimsecurity.com.

**Comment by lealog** [comment] 2020-04-08 13:51
@philrz : I will send a .pcap file from a Wi-Fi capture for your reference. I will talk directly with you on slack ;)

**Comment by philrz** [comment] 2020-04-09 00:12
Here's a summary of an offline discussion @lealog and I had regarding this issue.

I found that Brim did open the example pcapng file without complaint, but it couldn't do many interesting things with it. The reasons why as we now understand them:

1. It seems that Zeek (which generates the summary logs that form the initial Brim experience) does not do much with the 802.11 traffic on its own.
2. When the connection is established between AP and wi-fi client as part of the 802.11 communication, traffic would typically be encrypted (as was the case here). If this traffic could be decrypted before being processed by Zeek (such as [Wireshark can do](https://wiki.wireshark.org/HowToDecrypt802.11)) then potentially Zeek logs could be created for the IP traffic and flows for decrypted pcaps could be extracted.

**Comment by philrz** [comment] 2020-04-09 00:13
The Brim team discussed this issue, and we won't be able to work on it in the near future. We appreciate the input, and we'll leave the issue open to gather more interest & discussion from the community, and as possible inspiration for anyone that would like to tackle this.

**Comment by siskojr** [comment] 2020-05-06 23:40
We are closing this because we don't have capabilities to show this information. 

In the future we will support custom Zeek scripts. At that moment, if Zeek community has a 802.11 script, the user could just point Brim to it and  work as usual.

**Closed by siskojr** 2020-05-06 23:40 UTC
