### ISSUE TITLE
handle long messages from the back end

### ISSUE THREAD

**Issue by mikesbrown** [brimsec/brim#655] opened 2020-04-20 23:04 UTC
Sometimes backend messages, especially error messages, end up being so long that they break the bounds of their containing space.

See for example this:

![image](https://user-images.githubusercontent.com/16110130/79807698-8c0bd800-8320-11ea-8fad-6e26882e2786.png)

In this case the detail length is longer than the bounds of the box in which it is contained.

**Comment by philrz** [comment] 2020-04-20 23:49
This one is similar in spirit to https://github.com/brimsec/brim/issues/530. In that case I knew the error message had line breaks that would have made the messages fit if we'd obeyed the line breaks when presenting the message. As you seem to show here, though, there could also be such a thing as a very wide error message with no breaks that we'd want to wrap or present with a horizontal scrollbar. Hopefully both issues can be addressed with the same solution.

It doesn't seem like GitHub has a "relates to" linkage, so I'll establish a "block" dependency just so it's obvious the two are linked.

**Comment by philrz** [comment] 2020-04-20 23:57
Closing as a duplicate of https://github.com/brimsec/brim/issues/530.

**Closed by philrz** 2020-04-20 23:57 UTC
Labels: bug, duplicate
